### ISSUE TITLE
its not work ssl https://

### ISSUE THREAD

**Issue by lyarinet** [ay4t/WhatsAppHelper#2]
its not work ssl https://

**Comment by ay4t** [comment]
please describe in detail and clearly

**Comment by lyarinet** [comment]
im useing it on codeigniter and using ssl like 
https://exmple.com but is give error :
6789/send-message

**Comment by lyarinet** [comment]
Thank u  very very much quick response

**Comment by ay4t** [comment]
This problem solved with change country code in FormatPhoneTraits.php

![IMG_20221010_175628.jpg](https://user-images.githubusercontent.com/87152520/194850980-9d0e42d4-cb27-4a89-bf47-25896331f838.jpg)
